language: ruby
rvm:
- '2.3.1'
sudo: false
cache: bundler
before_install: 
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
before_script:
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_script.sh
addons:
  postgresql: '9.5'
env:
  - TEST_SUITE=rspec
  - TEST_SUITE=rubocop
script:
- bin/$TEST_SUITE
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
