language: ruby
rvm:
- '2.3.1'
sudo: false
cache: bundler
install: 
  - bundle install
  - bower install
addons:
  postgresql: '9.5'
env:
  - TEST_SUITE=rspec
  - TEST_SUITE=rubocop
script:
- bundle exec $TEST_SUITE
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
